/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorProfileRouteImport } from './routes/vendor.profile'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorInvoicesRouteImport } from './routes/vendor.invoices'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as ApiPublicSeedAdminRouteImport } from './routes/api.public.seed-admin'
import { Route as AdminVendorsIdRouteImport } from './routes/admin.vendors.$id'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorProfileRoute = VendorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorInvoicesRoute = VendorInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => VendorRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicSeedAdminRoute = ApiPublicSeedAdminRouteImport.update({
  id: '/api/public/seed-admin',
  path: '/api/public/seed-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsIdRoute = AdminVendorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminVendorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/vendor': typeof VendorRouteWithChildren
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/vendors': typeof AdminVendorsRouteWithChildren
  '/vendor/invoices': typeof VendorInvoicesRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/admin/vendors/$id': typeof AdminVendorsIdRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/vendors': typeof AdminVendorsRouteWithChildren
  '/vendor/invoices': typeof VendorInvoicesRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/admin': typeof AdminIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/admin/vendors/$id': typeof AdminVendorsIdRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/vendor': typeof VendorRouteWithChildren
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/vendors': typeof AdminVendorsRouteWithChildren
  '/vendor/invoices': typeof VendorInvoicesRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/admin/vendors/$id': typeof AdminVendorsIdRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/vendor'
    | '/admin/invoices'
    | '/admin/orders'
    | '/admin/vendors'
    | '/vendor/invoices'
    | '/vendor/orders'
    | '/vendor/profile'
    | '/admin/'
    | '/vendor/'
    | '/admin/vendors/$id'
    | '/api/public/seed-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/invoices'
    | '/admin/orders'
    | '/admin/vendors'
    | '/vendor/invoices'
    | '/vendor/orders'
    | '/vendor/profile'
    | '/admin'
    | '/vendor'
    | '/admin/vendors/$id'
    | '/api/public/seed-admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/vendor'
    | '/admin/invoices'
    | '/admin/orders'
    | '/admin/vendors'
    | '/vendor/invoices'
    | '/vendor/orders'
    | '/vendor/profile'
    | '/admin/'
    | '/vendor/'
    | '/admin/vendors/$id'
    | '/api/public/seed-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  VendorRoute: typeof VendorRouteWithChildren
  ApiPublicSeedAdminRoute: typeof ApiPublicSeedAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/profile': {
      id: '/vendor/profile'
      path: '/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof VendorProfileRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/invoices': {
      id: '/vendor/invoices'
      path: '/invoices'
      fullPath: '/vendor/invoices'
      preLoaderRoute: typeof VendorInvoicesRouteImport
      parentRoute: typeof VendorRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/seed-admin': {
      id: '/api/public/seed-admin'
      path: '/api/public/seed-admin'
      fullPath: '/api/public/seed-admin'
      preLoaderRoute: typeof ApiPublicSeedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors/$id': {
      id: '/admin/vendors/$id'
      path: '/$id'
      fullPath: '/admin/vendors/$id'
      preLoaderRoute: typeof AdminVendorsIdRouteImport
      parentRoute: typeof AdminVendorsRoute
    }
  }
}

interface AdminVendorsRouteChildren {
  AdminVendorsIdRoute: typeof AdminVendorsIdRoute
}

const AdminVendorsRouteChildren: AdminVendorsRouteChildren = {
  AdminVendorsIdRoute: AdminVendorsIdRoute,
}

const AdminVendorsRouteWithChildren = AdminVendorsRoute._addFileChildren(
  AdminVendorsRouteChildren,
)

interface AdminRouteChildren {
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminVendorsRoute: typeof AdminVendorsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminVendorsRoute: AdminVendorsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface VendorRouteChildren {
  VendorInvoicesRoute: typeof VendorInvoicesRoute
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorProfileRoute: typeof VendorProfileRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorInvoicesRoute: VendorInvoicesRoute,
  VendorOrdersRoute: VendorOrdersRoute,
  VendorProfileRoute: VendorProfileRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  VendorRoute: VendorRouteWithChildren,
  ApiPublicSeedAdminRoute: ApiPublicSeedAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
